/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CadastroCliente;
import controle.CadastroCompra;
import controle.CadastroFuncionario;
import controle.CadastroServico;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.ClienteTableModel;
import modelo.Compra;
import modelo.Endereco;
import modelo.Funcionario;
import modelo.Internet;
import modelo.Vendedor;

/**
 *
 * @author Amanda
 */
public class AtualizarCliente extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarCliente
     */
    
    int xMouse;
    int yMouse;
    
    private int codCliente;
    private int linhaTabela;
    private CadastroCompra cadCompra;
    private List<Compra> compras;
    private String funcLogado;
    
    public AtualizarCliente(int codCliente, int linhaTabela, String cpfFunc) throws IOException, ClassNotFoundException {
        cadCompra = new CadastroCompra();
        compras = cadCompra.listar();
        this.linhaTabela = linhaTabela;
        this.codCliente = codCliente;
        this.funcLogado = cpfFunc;
        initComponents();
        this.preencheCampos(codCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBarra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jAtualizarCliente = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        nome3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        telefone3 = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        email3 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        rua3 = new javax.swing.JTextField();
        bairro3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cidade3 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        cep3 = new javax.swing.JFormattedTextField();
        complemento3 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        pontoReferencia3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        dataNascimento1 = new javax.swing.JFormattedTextField();
        cpf3 = new javax.swing.JFormattedTextField();
        jLabel54 = new javax.swing.JLabel();
        servico1 = new javax.swing.JComboBox<>();
        rg3 = new javax.swing.JTextField();
        numero3 = new javax.swing.JTextField();
        jtNCartao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCodVenda = new javax.swing.JLabel();
        jtCodCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jBarra.setBackground(new java.awt.Color(28, 27, 27));
        jBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jBarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 25, 27));

        jLabel1.setBackground(new java.awt.Color(28, 27, 27));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jBarra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        jAtualizarCliente.setBackground(new java.awt.Color(255, 255, 255));
        jAtualizarCliente.setMinimumSize(new java.awt.Dimension(700, 502));
        jAtualizarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 204));
        jLabel24.setText("Atualizar Cliente");
        jAtualizarCliente.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 25));

        jLabel39.setBackground(new java.awt.Color(102, 102, 102));
        jLabel39.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Nome");
        jAtualizarCliente.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 26));
        jAtualizarCliente.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 640, 10));

        nome3.setForeground(new java.awt.Color(102, 102, 102));
        nome3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        nome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(nome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 228, 24));

        jLabel40.setBackground(new java.awt.Color(102, 102, 102));
        jLabel40.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Data de nascimento");
        jAtualizarCliente.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 26));

        jLabel41.setBackground(new java.awt.Color(102, 102, 102));
        jLabel41.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("CPF");
        jAtualizarCliente.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 34, 26));

        jLabel42.setBackground(new java.awt.Color(102, 102, 102));
        jLabel42.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setText("RG");
        jAtualizarCliente.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 28, 26));

        telefone3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            telefone3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone3.setText("");
        jAtualizarCliente.add(telefone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 102, 26));

        jLabel43.setBackground(new java.awt.Color(102, 102, 102));
        jLabel43.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Telefone");
        jAtualizarCliente.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 26));

        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("Dados Pessoais");
        jAtualizarCliente.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(102, 102, 102));
        jAtualizarCliente.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 5));

        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setText("Endereço");
        jAtualizarCliente.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(102, 102, 102));
        jAtualizarCliente.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 5));

        email3.setForeground(new java.awt.Color(102, 102, 102));
        email3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        email3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 251, 26));

        jLabel46.setBackground(new java.awt.Color(102, 102, 102));
        jLabel46.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Email");
        jAtualizarCliente.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 34, 26));

        jLabel47.setBackground(new java.awt.Color(102, 102, 102));
        jLabel47.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Rua/nº");
        jAtualizarCliente.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 26));

        rua3.setForeground(new java.awt.Color(102, 102, 102));
        rua3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        rua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rua3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(rua3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 228, 26));

        bairro3.setForeground(new java.awt.Color(102, 102, 102));
        bairro3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        bairro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(bairro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 169, 26));

        jLabel48.setBackground(new java.awt.Color(102, 102, 102));
        jLabel48.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Bairro");
        jAtualizarCliente.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 26));

        jLabel49.setBackground(new java.awt.Color(102, 102, 102));
        jLabel49.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setText("Cidade");
        jAtualizarCliente.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 26));

        cidade3.setForeground(new java.awt.Color(102, 102, 102));
        cidade3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cidade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(cidade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 280, 26));

        jLabel50.setBackground(new java.awt.Color(102, 102, 102));
        jLabel50.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("CEP");
        jAtualizarCliente.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 34, 26));

        cep3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            cep3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jAtualizarCliente.add(cep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 102, 26));

        complemento3.setForeground(new java.awt.Color(102, 102, 102));
        complemento3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        complemento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complemento3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(complemento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 200, 26));

        jLabel51.setBackground(new java.awt.Color(102, 102, 102));
        jLabel51.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("Complemento");
        jAtualizarCliente.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 26));

        pontoReferencia3.setForeground(new java.awt.Color(102, 102, 102));
        pontoReferencia3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pontoReferencia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoReferencia3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(pontoReferencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 169, 26));

        jLabel52.setBackground(new java.awt.Color(102, 102, 102));
        jLabel52.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 102, 102));
        jLabel52.setText("Ponto de Referência");
        jAtualizarCliente.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 26));

        btnAtualizar.setBackground(new java.awt.Color(0, 51, 204));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 140, 30));

        dataNascimento1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            dataNascimento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jAtualizarCliente.add(dataNascimento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 102, 26));

        cpf3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            cpf3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(cpf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 102, 26));

        jLabel54.setBackground(new java.awt.Color(102, 102, 102));
        jLabel54.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 102, 102));
        jLabel54.setText("Serviço");
        jAtualizarCliente.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 26));

        servico1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        servico1.setForeground(new java.awt.Color(102, 102, 102));
        servico1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 MB FIBRA", "20 MB FIBRA", "40 MB FIBRA", " " }));
        servico1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jAtualizarCliente.add(servico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 147, -1));

        rg3.setForeground(new java.awt.Color(102, 102, 102));
        rg3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        rg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(rg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 102, 26));

        numero3.setForeground(new java.awt.Color(102, 102, 102));
        numero3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ActionPerformed(evt);
            }
        });
        jAtualizarCliente.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 46, 26));
        jAtualizarCliente.add(jtNCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Nº Cartão:");
        jAtualizarCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Cod. Venda:");
        jAtualizarCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Cod. Cliente:");
        jAtualizarCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));
        jAtualizarCliente.add(jtCodVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        jAtualizarCliente.add(jtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jAtualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 676, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jAtualizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome3ActionPerformed

    private void email3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email3ActionPerformed

    private void rua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rua3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rua3ActionPerformed

    private void bairro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro3ActionPerformed

    private void cidade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade3ActionPerformed

    private void complemento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complemento3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complemento3ActionPerformed

    private void pontoReferencia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoReferencia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontoReferencia3ActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try {
            ClienteTableModel tabelaCliente = new ClienteTableModel();
            
            Compra compra = montaCompra();
            if(cadCompra.atualizar(compra) && tabelaCliente.atualizaTabela(linhaTabela, compra.getCliente())){
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso");
            } else{
                JOptionPane.showMessageDialog(null, "Falha na atualização");
            }   
        } catch (IOException ex) {
            ex.getStackTrace();
        } catch (ClassNotFoundException ex) {
           ex.getStackTrace();
        }
        
        dispose();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void cpf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf3ActionPerformed

    private void rg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg3ActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro3;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JFormattedTextField cep3;
    private javax.swing.JTextField cidade3;
    private javax.swing.JTextField complemento3;
    private javax.swing.JFormattedTextField cpf3;
    private javax.swing.JFormattedTextField dataNascimento1;
    private javax.swing.JTextField email3;
    private javax.swing.JPanel jAtualizarCliente;
    private javax.swing.JPanel jBarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jtCodCliente;
    private javax.swing.JLabel jtCodVenda;
    private javax.swing.JLabel jtNCartao;
    private javax.swing.JTextField nome3;
    private javax.swing.JTextField numero3;
    private javax.swing.JTextField pontoReferencia3;
    private javax.swing.JTextField rg3;
    private javax.swing.JTextField rua3;
    private javax.swing.JComboBox<String> servico1;
    private javax.swing.JFormattedTextField telefone3;
    // End of variables declaration//GEN-END:variables
    
    public Compra preencheCampos(int CodCliente){
        Compra compra = null;
        
        for(Compra c: compras){
            if(c.getCliente().getCodigo() == codCliente){
                compra = c;
                break;
            }
        }
        
        if(compra == null){
            JOptionPane.showMessageDialog(null, "Código da venda não existe");
        } else{
            jtCodCliente.setText(Integer.toString(compra.getCliente().getCodigo()));
            jtNCartao.setText(compra.getCliente().getNumeroDoCartao());
            jtCodVenda.setText(Integer.toString(compra.getCodigo()));
            nome3.setText(compra.getCliente().getNome());
            rg3.setText(compra.getCliente().getRg());
            cpf3.setText(compra.getCliente().getCpf());
            telefone3.setText(compra.getCliente().getTelefone());
            email3.setText(compra.getCliente().getEmail());
            dataNascimento1.setText(compra.getCliente().getDataDeNascimento());
            rua3.setText(compra.getCliente().getEndereco().getLogradouro());
            bairro3.setText(compra.getCliente().getEndereco().getLogradouro());
            numero3.setText(Integer.toString(compra.getCliente().getEndereco().getNumero()));
            complemento3.setText(compra.getCliente().getEndereco().getComplemento());
            pontoReferencia3.setText(compra.getCliente().getEndereco().getPontoDeReferencia());
            cidade3.setText(compra.getCliente().getEndereco().getCidade());
            cep3.setText(compra.getCliente().getEndereco().getCep());
        
            switch(compra.getServico().getCodigo()){
                case 1: 
                    servico1.setSelectedIndex(0);
                    break;
                case 2: 
                    servico1.setSelectedIndex(1);
                    break;
                case 3: 
                    servico1.setSelectedIndex(2);
                    break;
            }
        
        }
        return compra;
    }

    private Compra montaCompra() throws IOException, ClassNotFoundException {
        CadastroServico cadServ = new CadastroServico();
        CadastroCliente cadCliente = new CadastroCliente();
        Compra compra = new Compra();
        
        Cliente cliente = cadCliente.busca(Integer.parseInt(jtCodCliente.getText()));

        cliente.setNome(nome3.getText());
        cliente.setCpf(cpf3.getText());
        cliente.setDataDeNascimento(dataNascimento1.getText());
        cliente.setRg(rg3.getText());
        cliente.setEmail(email3.getText());
        cliente.setTelefone(telefone3.getText());
        
        Endereco endereco = new Endereco();
        
        endereco.setBairro(bairro3.getText());
        endereco.setCidade(cidade3.getText());
        endereco.setCep(cep3.getText());
        //Se o JTextField estiver vazio preenche o campo numero com o valor 0
        if(numero3.getText().isEmpty()){
            endereco.setNumero(0);
        } else{
            endereco.setNumero(Integer.parseInt(numero3.getText()));
        }
        endereco.setComplemento(complemento3.getText());
        endereco.setLogradouro(rua3.getText());
        endereco.setPontoDeReferencia(pontoReferencia3.getText());
        
        cliente.setEndereco(endereco);
        
        Internet serv = new Internet();
        
        switch (servico1.getSelectedIndex()) {
            case 0:
                serv = (Internet) cadServ.busca(1);
                break;
            case 1:
                serv = (Internet) cadServ.busca(2);
                break;
            case 2:
                serv = (Internet) cadServ.busca(3);
                break;
        }
        
        CadastroFuncionario cadFunc = new CadastroFuncionario();
        Funcionario func = cadFunc.busca(funcLogado);
        
        compra.setCodigo(Integer.parseInt(jtCodVenda.getText()));
        compra.setCliente(cliente);
        compra.setServico(serv);
        compra.setVendedor((Vendedor) func);
        return compra;
    }
    
}
